### ISSUE TITLE
Deselect doesn't clear filter on target widgets with AM Charts

### ISSUE THREAD

**Issue by bwood1** [hpcc-systems/Visualization#2245]
When you have an interaction and you deselect the source widget the target widget continues to have the filter applied. I tried several charts and this issue only seems to occur with AM Charts

Filtered correctly:
![screen shot 2017-07-19 at 3 24 38 pm](https://user-images.githubusercontent.com/2362888/28385537-7034903e-6c96-11e7-984c-7b9defd2651a.png)

Deselected but still being filtered:
![screen shot 2017-07-19 at 3 24 47 pm](https://user-images.githubusercontent.com/2362888/28385550-77aec79e-6c96-11e7-9661-7ecd66b01a07.png)

**Comment by GordonSmith** [comment]
@bwood1 I believe this is resolved in 1.16.0-rc4 please reopen if this is not the case.

**Comment by bwood1** [comment]
@GordonSmith I'm still having this issue with the following http://172.23.42.86:8081/?composition=1bd289a2-759d-4dfb-8dec-73134d5c1889

DSP Viz Version:  v1.16.0-rc4
DDL Viz Version:  v1.16.0-rc3

On load:

![screen shot 2017-08-04 at 11 29 47 am](https://user-images.githubusercontent.com/2362888/28975578-811d629e-7908-11e7-953c-84c8a8b1a34c.png)

On select:

![screen shot 2017-08-04 at 11 31 23 am](https://user-images.githubusercontent.com/2362888/28975579-85405354-7908-11e7-9372-a87908f39972.png)


On deselect:

![screen shot 2017-08-04 at 11 31 31 am](https://user-images.githubusercontent.com/2362888/28975584-8b3920b0-7908-11e7-9603-92ea29ffb857.png)

**Comment by GordonSmith** [comment]
Expired - please reopen if needed.
